### ISSUE TITLE
MITM模块的“发送到Web Fuzzer”不管用

### ISSUE THREAD

**Issue by dingdin9** [yaklang/yakit#50]
在手动劫持模式下，将抓到的请求按右键发送到Web Fuzzer，结果界面切换到了Web Fuzzer-[1]，但请求数据并没发送过去，必须手动复制粘贴过去。

**Comment by VillanCh** [comment]
十分感谢提醒，我看一下咋回事，应该是重构代码导致的小问题


十分感谢





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dingdin9 ***@***.***&gt;
发送时间: 2021年12月7日 18:49
收件人: yaklang/yakit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yaklang/yakit] MITM模块的“发送到Web Fuzzer”不管用 (Issue #50)





 
在手动劫持模式下，将抓到的请求按右键发送到Web Fuzzer，结果界面切换到了Web Fuzzer-[1]，但请求数据并没发送过去，必须手动复制粘贴过去。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vernon818** [comment]
你好，我们这边技术同学都没有复现到这个问题，你看加我微信我们详细聊一下，微信号：Juzi19880818

**Comment by VillanCh** [comment]
1.0.11-* 版本中修复该问题，感谢 @dingdin9 ding 大哥的反馈！

**Comment by Vernon818** [comment]
@dingdin9 为了感谢您对yak和yakit的支持，我们想邮寄一份小礼物给您，麻烦您微信添加一下：Juzi19880818，并备注好您的github账号。如已经添加账号，请微信联系我一下，谢谢
